/**
 * @file This file contains the initial seed data for the in-memory mock database.
 * In a real application, this data would likely be part of a database migration or seed script.
 * THIS IS FOR DEMONSTRATION PURPOSES ONLY.
 */

import type { Payment, Settlement, AuditLog, UATTestCase, Entity, TenantRecord, MerchantAccount, SettlementDestination, AllocationRule } from '@/lib/types';
import { subDays, subHours, subMinutes, formatISO } from 'date-fns';

const now = new Date();

// --- V2 Seed Data (Multi-Entity) ---

export const seedEntities: Entity[] = [
    // Level 0: The Processor
    {
        id: 'ent-speedypay',
        legalName: 'SpeedyPay Payments Inc.',
        displayName: 'SpeedyPay',
        entityType: 'speedypay',
        parentEntityId: null,
        status: 'active',
        metadata: { version: '1.0' },
        createdAt: formatISO(subDays(now, 200)),
        updatedAt: formatISO(subDays(now, 200)),
    },
    // Level 0: The Platform Itself
    {
        id: 'ent-platform',
        legalName: 'SpeedyPay Marketplace Inc.',
        displayName: 'SpeedyPay Platform',
        entityType: 'platform',
        parentEntityId: null,
        status: 'active',
        metadata: { version: '1.0' },
        createdAt: formatISO(subDays(now, 100)),
        updatedAt: formatISO(subDays(now, 100)),
    },
    // Level 1: A Tenant of the Platform
    {
        id: 'ent-collo',
        legalName: 'Collo Properties Inc.',
        displayName: 'Collo',
        entityType: 'tenant',
        parentEntityId: 'ent-platform',
        status: 'active',
        metadata: {},
        createdAt: formatISO(subDays(now, 50)),
        updatedAt: formatISO(subDays(now, 1)),
    },
    // Level 2: Merchants belonging to the Tenant
    {
        id: 'ent-starlight',
        legalName: 'Starlight Apartments Corp.',
        displayName: 'Starlight Apts',
        entityType: 'merchant',
        parentEntityId: 'ent-collo',
        status: 'active',
        metadata: { contactName: 'Alice Johnson', email: 'alice@starlight.com', mobile: '555-0101' },
        createdAt: formatISO(subDays(now, 45)),
        updatedAt: formatISO(subDays(now, 2)),
    },
    {
        id: 'ent-oceanview',
        legalName: 'Oceanview Properties Ltd.',
        displayName: 'Oceanview',
        entityType: 'merchant',
        parentEntityId: 'ent-collo',
        status: 'active',
        metadata: { contactName: 'Bob Williams', email: 'bob@oceanview.co', mobile: '555-0102' },
        createdAt: formatISO(subDays(now, 120)),
        updatedAt: formatISO(subDays(now, 15)),
    },
     {
        id: 'ent-greenwood',
        legalName: 'Greenwood Heights HOA LLC',
        displayName: 'Greenwood HOA',
        entityType: 'merchant',
        parentEntityId: 'ent-collo',
        status: 'active',
        metadata: { contactName: 'Carol White', email: 'carol@greenwood.org', mobile: '555-0103' },
        createdAt: formatISO(subDays(now, 200)),
        updatedAt: formatISO(subDays(now, 1)),
    },
];

export const seedTenants: TenantRecord[] = [
  {
    id: 'tnt-collo',
    entityId: 'ent-collo',
    tenantCode: 'COLLO',
    status: 'active',
    settings: { theme: 'default' },
    createdAt: formatISO(subDays(now, 50)),
    updatedAt: formatISO(subDays(now, 1)),
  },
];

export const seedAllocationRules: AllocationRule[] = [
    {
        id: 'ar-proc-1',
        tenantId: null,
        merchantAccountId: null,
        paymentMethod: 'all',
        ruleType: 'processing_fee',
        percentageValue: 0.5,
        flatValue: 5.00,
        recipientEntityId: 'ent-speedypay',
        priority: 10,
        active: true,
        createdAt: formatISO(subDays(now, 200)),
        updatedAt: formatISO(subDays(now, 200)),
    },
    {
        id: 'ar-plat-1',
        tenantId: null,
        merchantAccountId: null,
        paymentMethod: 'all',
        ruleType: 'platform_fee',
        percentageValue: 0.2,
        flatValue: null,
        recipientEntityId: 'ent-platform',
        priority: 20,
        active: true,
        createdAt: formatISO(subDays(now, 200)),
        updatedAt: formatISO(subDays(now, 200)),
    },
    {
        id: 'ar-tenant-collo',
        tenantId: 'tnt-collo',
        merchantAccountId: null,
        paymentMethod: 'all',
        ruleType: 'tenant_fee',
        percentageValue: 0.1,
        flatValue: null,
        recipientEntityId: 'ent-collo',
        priority: 30,
        active: true,
        createdAt: formatISO(subDays(now, 50)),
        updatedAt: formatISO(subDays(now, 1)),
    },
];

export const seedMerchantAccounts: MerchantAccount[] = [
  {
    id: 'mer-1',
    tenantId: 'tnt-collo',
    entityId: 'ent-starlight',
    onboardingStatus: 'completed',
    kycStatus: 'approved',
    settlementStatus: 'active',
    defaultSettlementDestinationId: 'sd-1',
    createdAt: formatISO(subDays(now, 45)),
    updatedAt: formatISO(subDays(now, 2)),
  },
  {
    id: 'mer-2',
    tenantId: 'tnt-collo',
    entityId: 'ent-oceanview',
    onboardingStatus: 'completed',
    kycStatus: 'approved',
    settlementStatus: 'active',
    defaultSettlementDestinationId: 'sd-2',
    createdAt: formatISO(subDays(now, 120)),
    updatedAt: formatISO(subDays(now, 15)),
  },
   {
    id: 'mer-3',
    tenantId: 'tnt-collo',
    entityId: 'ent-greenwood',
    onboardingStatus: 'completed',
    kycStatus: 'in_review',
    settlementStatus: 'active',
    defaultSettlementDestinationId: 'sd-3',
    createdAt: formatISO(subDays(now, 200)),
    updatedAt: formatISO(subDays(now, 1)),
  },
];

export const seedSettlementDestinations: SettlementDestination[] = [
    {
        id: 'sd-1',
        merchantAccountId: 'mer-1',
        destinationType: 'bank',
        accountName: 'Alice B Johnson',
        accountNumberMasked: '******7890',
        bankCode: 'BPI',
        providerReference: null,
        verificationStatus: 'verified',
        isDefault: true,
        createdAt: formatISO(subDays(now, 45)),
        updatedAt: formatISO(subDays(now, 2)),
    },
    {
        id: 'sd-2',
        merchantAccountId: 'mer-2',
        destinationType: 'wallet',
        accountName: 'Bob Williams',
        accountNumberMasked: '******4567',
        bankCode: 'GCASH',
        providerReference: null,
        verificationStatus: 'verified',
        isDefault: true,
        createdAt: formatISO(subDays(now, 120)),
        updatedAt: formatISO(subDays(now, 15)),
    },
    {
        id: 'sd-3',
        merchantAccountId: 'mer-3',
        destinationType: 'bank',
        accountName: 'Carol White',
        accountNumberMasked: '******3210',
        bankCode: 'BDO',
        providerReference: null,
        verificationStatus: 'pending',
        isDefault: true,
        createdAt: formatISO(subDays(now, 200)),
        updatedAt: formatISO(subDays(now, 1)),
    },
];


// --- Transactional Seed Data (updated to use new IDs) ---

export const seedPayments: Payment[] = [
  {
    id: 'pay-1',
    tenantId: 'tnt-collo',
    merchantId: 'mer-1', // Corresponds to MerchantAccount ID
    externalReference: 'ch_3Pq...V54',
    bookingReferenceOrInvoiceReference: 'inv-2024-07-001',
    customerName: 'David Miller',
    customerEmail: 'david.miller@example.com',
    grossAmount: 1250.00,
    currency: 'PHP',
    feeType: 'percentage',
    feeValue: 3.2,
    platformFeeAmount: 40.00,
    merchantNetAmount: 1210.00,
    paymentStatus: 'succeeded',
    settlementStatus: 'completed',
    remittanceStatus: 'sent',
    sourceChannel: 'Web',
    createdAt: formatISO(subDays(now, 1)),
    updatedAt: formatISO(subHours(now, 20)),
    providerPaymentUrl: 'https://test.e-mango.ph/cashier/pay?id=someid',
    providerCollectionRespCode: '00000000',
    providerCollectionRespMessage: 'Success',
    providerCollectionSignatureVerified: true,
    providerTransSeq: 'CP2024080112345',
    providerTransState: '00',
    providerStateLabel: 'succeeded',
    providerCreateTime: formatISO(subDays(now, 1)),
    providerNotifyTime: formatISO(subHours(now, 23)),
  },
  {
    id: 'pay-2',
    tenantId: 'tnt-collo',
    merchantId: 'mer-2',
    externalReference: 'ch_3Pq...X67',
    bookingReferenceOrInvoiceReference: 'inv-2024-07-002',
    customerName: 'Emily Clark',
    customerEmail: 'emily.clark@example.com',
    grossAmount: 800.00,
    currency: 'PHP',
    feeType: 'fixed',
    feeValue: 0.50,
    platformFeeAmount: 0.50,
    merchantNetAmount: 799.50,
    paymentStatus: 'pending',
    settlementStatus: 'pending',
    remittanceStatus: 'pending',
    sourceChannel: 'Manual',
    createdAt: formatISO(subHours(now, 5)),
    updatedAt: formatISO(subHours(now, 4)),
    providerPaymentUrl: 'https://test.e-mango.ph/cashier/pay?id=anotherid',
    providerCollectionRespCode: '00000000',
    providerCollectionRespMessage: 'Success',
    providerCollectionSignatureVerified: true,
    providerTransState: '07',
    providerStateLabel: 'to-be-paid',
  },
   {
    id: 'pay-3',
    tenantId: 'tnt-collo',
    merchantId: 'mer-1',
    externalReference: 'ch_3Pq...Y89',
    bookingReferenceOrInvoiceReference: 'inv-2024-07-003',
    customerName: 'Frank Harris',
    customerEmail: 'frank.harris@example.com',
    grossAmount: 350.00,
    currency: 'PHP',
    feeType: 'percentage',
    feeValue: 3.2,
    platformFeeAmount: 11.20,
    merchantNetAmount: 338.80,
    paymentStatus: 'failed',
    settlementStatus: 'N/A',
    remittanceStatus: 'N/A',
    sourceChannel: 'Web',
    createdAt: formatISO(subHours(now, 2)),
    updatedAt: formatISO(subHours(now, 1)),
  },
   {
    id: 'pay-4',
    tenantId: 'tnt-collo',
    merchantId: 'mer-3',
    externalReference: 'ch_3Pq...Z12',
    bookingReferenceOrInvoiceReference: 'inv-2024-06-105',
    customerName: 'Grace Lee',
    customerEmail: 'grace.lee@example.com',
    grossAmount: 2000.00,
    currency: 'PHP',
    feeType: 'percentage',
    feeValue: 2.5,
    platformFeeAmount: 50.00,
    merchantNetAmount: 1950.00,
    paymentStatus: 'succeeded',
    settlementStatus: 'completed',
    remittanceStatus: 'pending',
    sourceChannel: 'API',
    createdAt: formatISO(subDays(now, 5)),
    updatedAt: formatISO(subDays(now, 4)),
  },
  {
    id: 'pay-5',
    tenantId: 'tnt-collo',
    merchantId: 'mer-2',
    externalReference: 'N/A',
    bookingReferenceOrInvoiceReference: 'inv-2024-07-005',
    customerName: 'Demo Customer',
    customerEmail: 'demo@example.com',
    grossAmount: 150.00,
    currency: 'PHP',
    feeType: 'fixed',
    feeValue: 0.50,
    platformFeeAmount: 0.50,
    merchantNetAmount: 149.50,
    paymentStatus: 'succeeded',
    settlementStatus: 'completed',
    remittanceStatus: 'failed',
    sourceChannel: 'API',
    createdAt: formatISO(subDays(now, 2)),
    updatedAt: formatISO(subDays(now, 2)),
  }
];

export const seedSettlements: Settlement[] = [
  {
    id: 'set-a1b2c3d4',
    tenantId: 'tnt-collo',
    paymentId: 'pay-1',
    merchantId: 'mer-1',
    grossAmount: 1250.00,
    currency: 'PHP',
    platformFeeAmount: 40.00,
    merchantNetAmount: 1210.00,
    settlementStatus: 'completed',
    remittanceStatus: 'sent',
    payoutReference: `payout-set-a1b2c3d4`,
    failureReason: null,
    providerName: 'SpeedyPay',
    providerOrderSeq: 'set-a1b2c3d4',
    providerTransSeq: 'T12345678',
    providerRespCode: '00000000',
    providerRespMessage: 'Transaction Success',
    providerTransState: '00',
    providerTransStateLabel: 'succeeded',
    signatureVerified: true,
    payoutChannelProcId: 'BPI',
    payoutChannelDescription: 'BPI (InstaPay)',
    createdAt: formatISO(subHours(now, 23)),
    updatedAt: formatISO(subHours(now, 20)),
    lastQueryAt: formatISO(subHours(now, 20)),
    providerTimestamp: formatISO(subHours(now, 20)),
  },
  {
    id: 'set-c3d4e5f6',
    tenantId: 'tnt-collo',
    paymentId: 'pay-4',
    merchantId: 'mer-3',
    grossAmount: 2000.00,
    currency: 'PHP',
    platformFeeAmount: 50.00,
    merchantNetAmount: 1950.00,
    settlementStatus: 'completed',
    remittanceStatus: 'pending',
    payoutReference: null,
    failureReason: null,
    createdAt: formatISO(subDays(now, 5)),
    updatedAt: formatISO(subDays(now, 4)),
  },
  {
    id: 'set-d4e5f6g7',
    tenantId: 'tnt-collo',
    paymentId: 'pay-5',
    merchantId: 'mer-2',
    grossAmount: 150.00,
    currency: 'PHP',
    platformFeeAmount: 0.50,
    merchantNetAmount: 149.50,
    settlementStatus: 'completed',
    remittanceStatus: 'failed',
    payoutReference: 'payout-set-d4e5f6g7',
    failureReason: 'Remittance transfer failed due to invalid beneficiary details or network error.',
    providerName: 'SpeedyPay',
    providerOrderSeq: 'set-d4e5f6g7',
    providerTransSeq: 'T54321098',
    providerRespCode: 'ER100100',
    providerRespMessage: 'Transaction Failed: Invalid Account',
    providerTransState: '01',
    providerTransStateLabel: 'failed',
    signatureVerified: true,
    payoutChannelProcId: 'GCASH',
    payoutChannelDescription: 'GCash',
    createdAt: formatISO(subDays(now, 2)),
    updatedAt: formatISO(subDays(now, 2)),
    lastQueryAt: formatISO(subDays(now, 2)),
    providerTimestamp: formatISO(subDays(now, 2)),
  }
];

export const seedAuditLogs: AuditLog[] = [
    {
        id: 'log-1',
        timestamp: formatISO(subMinutes(now, 15)),
        eventType: 'user.login',
        user: 'admin@speedypay.com',
        details: 'User logged in successfully from IP 192.168.1.1',
        entityId: 'usr_admin',
        entityType: 'user',
    },
    {
        id: 'log-2',
        timestamp: formatISO(subHours(now, 23)),
        eventType: 'payment.created',
        user: 'System',
        details: 'Payment created via Web channel.',
        entityId: 'pay-1',
        entityType: 'payment',
    },
];

export const uatTestCases: UATTestCase[] = [
    {
        id: 'COL-01',
        section: 'Collections',
        title: 'Create Collection Payment',
        description: 'Verifies payment link creation. A successful payment via the link should trigger a webhook, which in turn automatically creates a "completed" settlement record.',
        actionLabel: 'Create Test Payment',
        requiresInput: 'payment_amount'
    },
    {
        id: 'COL-02',
        section: 'Collections',
        title: 'Query Collection Status',
        description: 'Verifies direct, server-to-server querying of a pending payment from the provider. This confirms API connectivity and signature generation.',
        actionLabel: 'Query Payment',
        requiresInput: 'latest_payment'
    },
    {
        id: 'PAY-01',
        section: 'Payouts',
        title: 'Initiate Payout/Remittance',
        description: 'Verifies the remittance creation process for a settled transaction. Requires a settlement with status "completed" and remittance "pending".',
        actionLabel: 'Initiate Payout',
        requiresInput: 'latest_settlement'
    },
    {
        id: 'PAY-02',
        section: 'Payouts',
        title: 'Query Payout Status',
        description: 'Verifies direct, server-to-server querying of an initiated payout. This confirms API connectivity and correct request formatting for the payout API.',
        actionLabel: 'Query Payout',
        requiresInput: 'latest_settlement'
    },
     {
        id: 'SYS-01',
        section: 'System & Treasury',
        title: 'Query Collection Balance',
        description: 'Verifies API credentials and connectivity by querying the live balance from the collections provider.',
        actionLabel: 'Query Balance',
    },
     {
        id: 'SYS-02',
        section: 'System & Treasury',
        title: 'Query Payout Balance',
        description: 'Verifies API credentials and connectivity by querying the live balance from the payouts provider.',
        actionLabel: 'Query Balance',
    },
];
