/**
 * @file This file contains the initial seed data for the in-memory mock database.
 * In a real application, this data would likely be part of a database migration or seed script.
 * THIS IS FOR DEMONSTRATION PURPOSES ONLY.
 */

import type { Merchant, Payment, Settlement, AuditLog, UATTestCase } from '@/lib/types';
import { subDays, subHours, subMinutes, formatISO } from 'date-fns';

const now = new Date();

export const seedMerchants: Merchant[] = [
  {
    id: 'mer-1',
    businessName: 'Starlight Apartments',
    displayName: 'Starlight Apts',
    contactName: 'Alice Johnson',
    email: 'alice@starlight.com',
    mobile: '555-0101',
    settlementAccountName: 'Alice B Johnson',
    settlementAccountNumberOrWalletId: '1234567890',
    defaultPayoutChannel: 'BPI',
    status: 'active',
    onboardingStatus: 'completed',
    propertyAssociations: ['P-001', 'P-002'],
    defaultFeeType: 'percentage',
    defaultFeeValue: 3.2,
    notes: 'Primary client for property management. High volume.',
    createdAt: formatISO(subDays(now, 45)),
    updatedAt: formatISO(subDays(now, 2)),
  },
  {
    id: 'mer-2',
    businessName: 'Oceanview Properties',
    displayName: 'Oceanview',
    contactName: 'Bob Williams',
    email: 'bob@oceanview.co',
    mobile: '555-0102',
    settlementAccountName: 'Bob Williams',
    settlementAccountNumberOrWalletId: '09171234567',
    defaultPayoutChannel: 'GCASH',
    status: 'active',
    onboardingStatus: 'completed',
    propertyAssociations: ['P-003'],
    defaultFeeType: 'fixed',
    defaultFeeValue: 0.50,
    notes: 'Handles luxury rentals. Prefers wallet payouts.',
    createdAt: formatISO(subDays(now, 120)),
    updatedAt: formatISO(subDays(now, 15)),
  },
   {
    id: 'mer-3',
    businessName: 'Greenwood Heights HOA',
    displayName: 'Greenwood HOA',
    contactName: 'Carol White',
    email: 'carol@greenwood.org',
    mobile: '555-0103',
    settlementAccountName: 'Carol White',
    settlementAccountNumberOrWalletId: '9876543210',
    defaultPayoutChannel: 'BDO',
    status: 'active',
    onboardingStatus: 'completed',
    propertyAssociations: ['P-004'],
    defaultFeeType: 'percentage',
    defaultFeeValue: 2.5,
    notes: 'Awaiting updated compliance documents.',
    createdAt: formatISO(subDays(now, 200)),
    updatedAt: formatISO(subDays(now, 1)),
  },
];

export const seedPayments: Payment[] = [
  {
    id: 'pay-1',
    externalReference: 'ch_3Pq...V54',
    bookingReferenceOrInvoiceReference: 'inv-2024-07-001',
    customerName: 'David Miller',
    customerEmail: 'david.miller@example.com',
    merchantId: 'mer-1',
    grossAmount: 1250.00,
    currency: 'PHP',
    feeType: 'percentage',
    feeValue: 3.2,
    platformFeeAmount: 40.00,
    merchantNetAmount: 1210.00,
    paymentStatus: 'succeeded',
    settlementStatus: 'completed',
    remittanceStatus: 'sent',
    sourceChannel: 'Web',
    createdAt: formatISO(subDays(now, 1)),
    updatedAt: formatISO(subHours(now, 20)),
    providerPaymentUrl: 'https://test.e-mango.ph/cashier/pay?id=someid',
    providerCollectionRespCode: '00000000',
    providerCollectionRespMessage: 'Success',
    providerCollectionSignatureVerified: true,
    providerTransSeq: 'CP2024080112345',
    providerTransState: '00',
    providerStateLabel: 'succeeded',
    providerCreateTime: formatISO(subDays(now, 1)),
    providerNotifyTime: formatISO(subHours(now, 23)),
  },
  {
    id: 'pay-2',
    externalReference: 'ch_3Pq...X67',
    bookingReferenceOrInvoiceReference: 'inv-2024-07-002',
    customerName: 'Emily Clark',
    customerEmail: 'emily.clark@example.com',
    merchantId: 'mer-2',
    grossAmount: 800.00,
    currency: 'PHP',
    feeType: 'fixed',
    feeValue: 0.50,
    platformFeeAmount: 0.50,
    merchantNetAmount: 799.50,
    paymentStatus: 'pending',
    settlementStatus: 'pending',
    remittanceStatus: 'pending',
    sourceChannel: 'Manual',
    createdAt: formatISO(subHours(now, 5)),
    updatedAt: formatISO(subHours(now, 4)),
    providerPaymentUrl: 'https://test.e-mango.ph/cashier/pay?id=anotherid',
    providerCollectionRespCode: '00000000',
    providerCollectionRespMessage: 'Success',
    providerCollectionSignatureVerified: true,
    providerTransState: '07',
    providerStateLabel: 'to-be-paid',
  },
   {
    id: 'pay-3',
    externalReference: 'ch_3Pq...Y89',
    bookingReferenceOrInvoiceReference: 'inv-2024-07-003',
    customerName: 'Frank Harris',
    customerEmail: 'frank.harris@example.com',
    merchantId: 'mer-1',
    grossAmount: 350.00,
    currency: 'PHP',
    feeType: 'percentage',
    feeValue: 3.2,
    platformFeeAmount: 11.20,
    merchantNetAmount: 338.80,
    paymentStatus: 'failed',
    settlementStatus: 'N/A',
    remittanceStatus: 'N/A',
    sourceChannel: 'Web',
    createdAt: formatISO(subHours(now, 2)),
    updatedAt: formatISO(subHours(now, 1)),
  },
   {
    id: 'pay-4',
    externalReference: 'ch_3Pq...Z12',
    bookingReferenceOrInvoiceReference: 'inv-2024-06-105',
    customerName: 'Grace Lee',
    customerEmail: 'grace.lee@example.com',
    merchantId: 'mer-3',
    grossAmount: 2000.00,
    currency: 'PHP',
    feeType: 'percentage',
    feeValue: 2.5,
    platformFeeAmount: 50.00,
    merchantNetAmount: 1950.00,
    paymentStatus: 'succeeded',
    settlementStatus: 'completed',
    remittanceStatus: 'pending',
    sourceChannel: 'API',
    createdAt: formatISO(subDays(now, 5)),
    updatedAt: formatISO(subDays(now, 4)),
  },
  {
    id: 'pay-5',
    externalReference: 'N/A',
    bookingReferenceOrInvoiceReference: 'inv-2024-07-005',
    customerName: 'Demo Customer',
    customerEmail: 'demo@example.com',
    merchantId: 'mer-2',
    grossAmount: 150.00,
    currency: 'PHP',
    feeType: 'fixed',
    feeValue: 0.50,
    platformFeeAmount: 0.50,
    merchantNetAmount: 149.50,
    paymentStatus: 'succeeded',
    settlementStatus: 'completed',
    remittanceStatus: 'failed',
    sourceChannel: 'API',
    createdAt: formatISO(subDays(now, 2)),
    updatedAt: formatISO(subDays(now, 2)),
  }
];

export const seedSettlements: Settlement[] = [
  {
    id: 'set-a1b2c3d4',
    paymentId: 'pay-1',
    merchantId: 'mer-1',
    grossAmount: 1250.00,
    platformFeeAmount: 40.00,
    merchantNetAmount: 1210.00,
    settlementStatus: 'completed',
    remittanceStatus: 'sent',
    payoutReference: `payout-set-a1b2c3d4`,
    failureReason: null,
    providerName: 'SpeedyPay',
    providerOrderSeq: 'set-a1b2c3d4',
    providerTransSeq: 'T12345678',
    providerRespCode: '00000000',
    providerRespMessage: 'Transaction Success',
    providerTransState: '00',
    providerTransStateLabel: 'succeeded',
    signatureVerified: true,
    payoutChannelProcId: 'BPI',
    payoutChannelDescription: 'BPI (InstaPay)',
    createdAt: formatISO(subHours(now, 23)),
    updatedAt: formatISO(subHours(now, 20)),
    lastQueryAt: formatISO(subHours(now, 20)),
    providerTimestamp: formatISO(subHours(now, 20)),
  },
  {
    id: 'set-c3d4e5f6',
    paymentId: 'pay-4',
    merchantId: 'mer-3',
    grossAmount: 2000.00,
    platformFeeAmount: 50.00,
    merchantNetAmount: 1950.00,
    settlementStatus: 'completed',
    remittanceStatus: 'pending',
    payoutReference: null,
    failureReason: null,
    createdAt: formatISO(subDays(now, 5)),
    updatedAt: formatISO(subDays(now, 4)),
  },
  {
    id: 'set-d4e5f6g7',
    paymentId: 'pay-5',
    merchantId: 'mer-2',
    grossAmount: 150.00,
    platformFeeAmount: 0.50,
    merchantNetAmount: 149.50,
    settlementStatus: 'completed',
    remittanceStatus: 'failed',
    payoutReference: 'payout-set-d4e5f6g7',
    failureReason: 'Remittance transfer failed due to invalid beneficiary details or network error.',
    providerName: 'SpeedyPay',
    providerOrderSeq: 'set-d4e5f6g7',
    providerTransSeq: 'T54321098',
    providerRespCode: 'ER100100',
    providerRespMessage: 'Transaction Failed: Invalid Account',
    providerTransState: '01',
    providerTransStateLabel: 'failed',
    signatureVerified: true,
    payoutChannelProcId: 'GCASH',
    payoutChannelDescription: 'GCash',
    createdAt: formatISO(subDays(now, 2)),
    updatedAt: formatISO(subDays(now, 2)),
    lastQueryAt: formatISO(subDays(now, 2)),
    providerTimestamp: formatISO(subDays(now, 2)),
  }
];

export const seedAuditLogs: AuditLog[] = [
    {
        id: 'log-1',
        timestamp: formatISO(subMinutes(now, 15)),
        eventType: 'user.login',
        user: 'admin@speedypay.com',
        details: 'User logged in successfully from IP 192.168.1.1',
        entityId: 'usr_admin',
        entityType: 'user',
    },
    {
        id: 'log-2',
        timestamp: formatISO(subHours(now, 23)),
        eventType: 'payment.created',
        user: 'System',
        details: 'Payment created via Web channel.',
        entityId: 'pay-1',
        entityType: 'payment',
    },
];

export const uatTestCases: UATTestCase[] = [
    {
        id: 'COL-01',
        section: 'Collections',
        title: 'Create Collection Payment',
        description: 'Verifies payment link creation. A successful payment via the link should trigger a webhook, which in turn automatically creates a "completed" settlement record.',
        actionLabel: 'Create Test Payment',
        requiresInput: 'payment_amount'
    },
    {
        id: 'COL-02',
        section: 'Collections',
        title: 'Query Collection Status',
        description: 'Verifies direct, server-to-server querying of a pending payment from the provider. This confirms API connectivity and signature generation.',
        actionLabel: 'Query Payment',
        requiresInput: 'latest_payment'
    },
    {
        id: 'PAY-01',
        section: 'Payouts',
        title: 'Initiate Payout/Remittance',
        description: 'Verifies the remittance creation process for a settled transaction. Requires a settlement with status "completed" and remittance "pending".',
        actionLabel: 'Initiate Payout',
        requiresInput: 'latest_settlement'
    },
    {
        id: 'PAY-02',
        section: 'Payouts',
        title: 'Query Payout Status',
        description: 'Verifies direct, server-to-server querying of an initiated payout. This confirms API connectivity and correct request formatting for the payout API.',
        actionLabel: 'Query Payout',
        requiresInput: 'latest_settlement'
    },
     {
        id: 'SYS-01',
        section: 'System & Treasury',
        title: 'Query Collection Balance',
        description: 'Verifies API credentials and connectivity by querying the live balance from the collections provider.',
        actionLabel: 'Query Balance',
    },
     {
        id: 'SYS-02',
        section: 'System & Treasury',
        title: 'Query Payout Balance',
        description: 'Verifies API credentials and connectivity by querying the live balance from the payouts provider.',
        actionLabel: 'Query Balance',
    },
];
